name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup git config
        run: |
          # setup the username and email
          git config user.name "GitHub-Actions Bot"
          git config user.email "<>"
      - name: Set up Java 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11.0.9
          java-package: jdk
          architecture: x64
      - name: Create maven settings.xml with credentials
        uses: whelk-io/maven-settings-xml-action@v2
        with:
          servers: '[
                      { "id": "nexus.terrestris.de", "username": "${{ secrets.NEXUS_USER }}", "password": "${{ secrets.NEXUS_PASSWORD }}" },
                      { "id": "terrestris-nexus", "username": "${{ secrets.NEXUS_USER }}", "password": "${{ secrets.NEXUS_PASSWORD }}" },
                      { "id": "terrestris-nexus-snapshots", "username": "${{ secrets.NEXUS_USER }}", "password": "${{ secrets.NEXUS_PASSWORD }}" }
                    ]'
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies ⏬
        run: npm ci
      - name: Build 🏗️
        run: npm run build
      - name: Release 🚀
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release