name: Release

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: https://nexus.terrestris.de/repository/terrestris-public/

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies ⏬
        run: npm ci

      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Login to Nexus
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ${{ env.DOCKER_REGISTRY }}/<name>:latest
            ${{ env.DOCKER_REGISTRY }}/<name>:${{ steps.semantic.outputs.new_release_version }}
          load: true

      - name: Push docker image to Nexus
        run: |
          docker push ${{ env.DOCKER_REGISTRY }}/<name>:latest
          docker push ${{ env.DOCKER_REGISTRY }}/<name>:${{ steps.semantic.outputs.new_release_version }}
