name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Java 17
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 17
          java-package: jdk
          architecture: x64
      - name: Create maven settings.xml with credentials
        uses: whelk-io/maven-settings-xml-action@v2
        with:
          servers: '[
                      { "id": "nexus.terrestris.de", "username": "${{ secrets.NEXUS_USER }}", "password": "${{ secrets.NEXUS_PASSWORD }}" },
                      { "id": "terrestris-nexus", "username": "${{ secrets.NEXUS_USER }}", "password": "${{ secrets.NEXUS_PASSWORD }}" },
                      { "id": "terrestris-nexus-snapshots", "username": "${{ secrets.NEXUS_USER }}", "password": "${{ secrets.NEXUS_PASSWORD }}" }
                    ]'
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies ⏬
        run: npm ci
      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build and release
        uses: qcastel/github-actions-maven-release@v1.12.25
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk/
          SKIP_GIT_SANITY_CHECK: true
        with:
          release-branch-name: "main"
          git-release-bot-name: "semantic-release-bot"
          git-release-bot-email: "info@terrestris.de"

          maven-repo-server-id: terrestris-nexus
          maven-repo-server-username: ${{ secrets.NEXUS_USER }}
          maven-repo-server-password: ${{ secrets.NEXUS_PASSWORD }}

          maven-args: "-Dmaven.javadoc.skip=true -DskipTests"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          maven-development-version-number: ${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.nextIncrementalVersion}-SNAPSHOT
          maven-release-version-number: ${{ steps.semantic.outputs.new_release_version }}
